apiVersion: v1
kind: Service   # Service相当于负载均衡代理
metadata:
  name: svc-apigw
  labels:
    app: svc-apigw
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: svc-apigw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: svc-apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-apigw
  template:
    metadata:
      labels:
        app: svc-apigw
    spec:
      containers:
        - name: svc-apigw
          image: micro_gateway
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8081 # 监听8081端口
            name: apigw-port
          volumeMounts:
            - mountPath: /src/gateway/*
              name: file-volume
      volumes:
        - name: file-volume